version: '3'

services: 
  ## Server
  server:
    build: ./server
    # depends_on: 
    #   - cert-provider
    # networks: 
    #   - frontend
    #   - backend
    expose: 
      - 8081
    ports:
      - 8081:8081
    volumes: 
      - ./server/src:/srv/server/src
      - certs:/etc/ssl/certs:ro
    command: yarn start 8081

  ## Cert-Provider
  cert-provider:
    image: pgarrett/openssl-alpine
    stdin_open: true
    environment:
      - COUNTY=AU
      - STATE=Some
      - LOCATION=North
      - ORGANISATION=South
      - ISSUER_CN=Me
      - PUBLIC_CN=localhost
      - ISSUER_NAME=Me
      - PUBLIC_NAME=localhost
    volumes: 
      - certs:/etc/ssl/certs

# networks: 
#   frontend:
#     internal: false
#   backend:
#     internal: true

volumes:
  certs: