version: '3'

services: 
  ## Server
  server:
    build: ./server
    expose: 
      - 443
    ports:
      - 443:443
    volumes: 
      - ./server/src:/srv/server/src
      - certs:/etc/letsencrypt/live:ro
    command: yarn start 443

  ## Cert-Provider
  cert-provider:
    image: certbot/certbot
    expose:
      - 80
    ports:
      - 80:80
    volumes:
      - certs:/etc/letsencrypt/live
    command: certonly --standalone

volumes:
  certs: